### PR TITLE
feat(bin): pass through harmony flag to node

### PR DESCRIPTION
**Pull request by MeirionHughes**
* allow using harmony features when running ts-node. 
* support native async-iteration. 

I'm doing work with `for await` and `[Symbol.asyncIterator]` both are supported in node>=7 with `--harmony-async-iteration`. However, currently ts-node doesn't allow enabling this via args.

### CODE REVIEW

**Comment by blakeembrey** [comment]
@MeirionHughes These flags are already provided by `v8flags`, since they come from V8. You should already be able to use them if your node.js version supports it.

**Comment by blakeembrey** [comment]
image

**Comment by MeirionHughes** [comment]
okay, I see the issue; `--harmony-async-iteration` doesn't work via `ts-node`, but does with `node`. However, `--harmony_async_iteration` does work.

**Comment by blakeembrey** [comment]
That's odd, thanks for the heads up. Anything `ts-node` can do to avoid the processing overhead of adding new flags each time is great. I'm wondering if there's a better way to handle this instead of trying to detect what node.js supports - likely a blacklist of `ts-node` flags instead of a whitelist of `node` flags.

**Pull request closed without merging**
