### PR TITLE
Added `--inspect-brk` to knownFlags.

### PR DESCRIPTION
**Pull request by Deilan**
#342

### CODE REVIEW

**Comment by borekb** [comment]
How is this supposed to work please? When I do 

```
tsnode --inspect-brk myscript.ts
```

it enters interactive mode. When I do

```
tsnode --inspect-brk=9229 myscript.ts
```

it runs the script without debugging. Maybe I'm misunderstanding how this should work.

Version info:

```
$ node_modules/.bin/ts-node -v
ts-node v6.0.3
node v8.11.1
typescript v2.8.3
```

**Comment by borekb** [comment]
Oh I missed that! Ironically, I already use `node -r ts-node/register --inspect-brk myscript.ts` to debug my scripts, just thought that there is an easier form `ts-node --inspect-brk myscript.ts` by misreading this PR.

Out of curiosity, could the nicer form also work, or is it technically impossible / complicated?

**Comment by blakeembrey** [comment]
It used to be supported but had technical issues and resulted in numerous PR additions such as this one. Since I don’t have the personal bandwitch to respond to this module and all the others I work on, plus work, I opted to go the simpler path with less issues.

**Comment by blakeembrey** [comment]
Feel free to check the changelog for a little more context, support was removed in the last major version.

**Comment by borekb** [comment]
Makes sense, thanks for the explanation.

**Pull request merged**
