### PR TITLE
Added logo.svg

### PR DESCRIPTION
**Pull request by kumarashwin**
**Relevant Issue:** https://github.com/TypeStrong/ts-node/issues/470

**UPDATE:** Seems like it's not working as I expected across multiple browsers. I'm going to go back home today and have a look at making sure the text is displayed properly. Unless someone else feels like they can fix it with the `.svg` provided. :+1:

### CODE REVIEW

**Comment by blakeembrey** [comment]
@kumarashwin Would the font issue be caused by using `'Neutra Text'`? I could have a look, maybe we can turn the text into objects instead or I'll just re-export it as `png` if that doesn't work.

**Comment by kumarashwin** [comment]
@blakeembrey Your clue about turning the text to path had me do some research and I think I've managed to fix it in the latest update. Let me know if it shows up fine on your side.

**Comment by blakeembrey** [comment]
Looks great on my end now 👍

**Comment by blakeembrey** [comment]
Would you like me to go through and delete some of the Inkscape specific comments for you? Seems odd it would export with things such as an attribute of where you exported it to on your desktop (maybe there's a "web export mode")?

**Comment by kumarashwin** [comment]
@blakeembrey I believe that should take care of it. : )

**Comment by kumarashwin** [comment]
@blakeembrey I tried that first but it didn't look the best (IMO) since it caused dissonance with the main hexagon having the gradients and then the other two smaller ones in `node` having a solid color.

**Pull request merged**
