### PR TITLE
TS 5.0 Supporting Multiple Configuration Files in extends

### LINKED ISSUE #1954: Add support for TS 5.0 "extends" array
TS 5.0 adds support for "extends" to be an array of one or more extended configs, not just a single config.

https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-beta/#supporting-multiple-configuration-files-in-extends

We can do the same, also merging `ts-node` options from multiple tsconfigs.

### PR DESCRIPTION
**Pull request by cspotcode**
Fixes #1954

### CODE REVIEW

**Comment by cspotcode** [comment]
No set time.  I recommend installing from git in the meantime.

https://github.com/TypeStrong/ts-node/discussions/1977

**Comment by cspotcode** [comment]
To be sure we're on the same page, you're in an environment where the `prepare` script will not run for a git dep?  But yeah, you can go with any workflow where you `npm pack` and then put that tarball somewhere and use it.

**Comment by WoodyWoodsta** [comment]
In my environment, `ts-node` is a transitive dependency and we use `yarn` as a package manager. I believe `yarn` > 1 doesn't support `prepare`: https://github.com/yarnpkg/berry/issues/2305

**Comment by cspotcode** [comment]
Thanks for bringing that to my attention.  I've switched us over to using `prepack` instead #1979

**Comment by WoodyWoodsta** [comment]
No problem - thank you for making that change!

**Comment by DreamOfIce** [comment]
Is there anything preventing us from releasing a patch version? 
Installing from git is slow and often reports errors

**Comment by slavafomin** [comment]
Hello! Thank you for your hard work, however, what's blocking this patch from being released? It's been half a year already and a lot of people are still having trouble with this issue.

**Comment by roydukkey** [comment]
If your still waiting for this release, you might look into [tsx](https://github.com/esbuild-kit/tsx).

**Comment by slavafomin** [comment]
> If your still waiting for this release, you might look into [tsx](https://github.com/esbuild-kit/tsx).

Wow, it looks pretty cool. Thank you for mentioning it. I will definitely give it a try.

**Comment by Elyahou** [comment]
Any news about the release ?

**Comment by FreePhoenix888** [comment]
I am going to use typescript and node instead of using ts-node because this takes so long

**Comment by mrkjdy** [comment]
@blakeembrey Can a patch version be released to fix this problem as well? I was hoping that this was available in `10.9.2`, but it's still not.

**Comment by cAttte** [comment]
will this very simple feature ever be released?

**Pull request merged**
