### PR TITLE
Change outDir so that its on the same level as the typescript project

### PR DESCRIPTION
**Pull request by rundef**
Please check out the following issue https://github.com/istanbuljs/nyc/issues/314 to understand why I opened this pull request

Thank you !

### CODE REVIEW

**Comment by blakeembrey** [comment]
There doesn't seem to be any guarantee this won't be broken again in the future. I think it'd be better to move back to manual source map parsing and rewriting to make these absolute paths as neither of those `../..` mean anything and I have no idea why they are there. E.g. https://github.com/TypeStrong/ts-node/commit/2d20d65819ad8a474ce37d5310da233d4b51426b.

**Comment by rundef** [comment]
Thanks for the quick reply

I've changed the sourcemap mapping back to absolute URLs.

Let me give you a better picture of what's going on with the nyc+ts-node problem, there may be a better way to fix that problem ?

1. nyc requires **ts-node/register** 
2. As an example, let's say my project only contain one file: **app/helpers/Logger.ts** - it gets compiled to **tmpXYZ/app/helpers/Logger.js** (because _ts-node_ sets the _outDir_ to **tmpXYZ**)
3. The base64 sourcemap comments at the end of the file contains a sources array with the value of **../../../app/helpers/Logger.ts** which is absolutely the correct relative path
4. nyc doesn't know that ts-node compiled the file into a sub-directory, it simply does a *join(ts_file, sourcemap.sources)*, which ends up being the incorrect path

**Comment by blakeembrey** [comment]
Thanks! It seems that method no longer exists in `typescript@next` so the tests are failing. It might be easier to keep the `inlineSources: true` flag and just update the filenames instead. That way we can avoid that API call altogether. What do you think?

**Comment by blakeembrey** [comment]
Merged it https://github.com/TypeStrong/ts-node/commit/85745f574f80e3a2a53337bf60c33d00f25cf469.

**Comment by rundef** [comment]
:+1: thanks ! hopefully this gets pushed on npm soon

**Pull request closed without merging**
