### PR TITLE
Clarify README for tsx/jsx endings.

### LINKED ISSUE #1178: SyntaxError with tsx file ending.
### Expected Behavior

According to the readme, ts-node registers itself for file endings `.tsx?`, i.e. `.ts` and `.tsx`. Therefore the behavior should be the same for both file endings.

### Actual Behavior

`SyntaxError: Cannot use import statement outside a module` with.tsx file

### Steps to reproduce the problem

```sh
# create a test.ts file
$ echo "import * as path from 'path'" >> test.ts
$ echo "console.log(Object.keys(path))" >> test.ts

# works as expected
$ ts-node test.ts
[
  'resolve',    'normalize',
  'isAbsolute', 'join',
  'relative',   'toNamespacedPath',
  'dirname',    'basename',
  'extname',    'format',
  'parse',      'sep',
  'delimiter',  'win32',
  'posix',      '_makeLong'
]

# copy to test.tsx
$ cp test.ts test.tsx

# try running it with ts-node
$ ts-node test.tsx
(node:19628) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\aval\tsdev\chroma.ts\ts-node-error\test.tsx:1
import * as path from 'path'
^^^^^^

SyntaxError: Cannot use import statement outside a module
...

# -O does nothing
$ ts-node -O "{\"module\":\"commonjs\"}" test.tsx
(node:1784) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\aval\tsdev\chroma.ts\ts-node-error\test.tsx:1
import * as path from 'path'
^^^^^^

SyntaxError: Cannot use import statement outside a module
...


```

### Minimal reproduction

see above

### Specifications

* ts-node v9.1.1
* node v14.15.2
* compiler v4.1.3

* tsconfig.json, if you're using one: none, see above
* Operating system and version:
* 
image

* If Windows, are you using WSL or WSL2?: no

### PR DESCRIPTION
**Pull request by NaridaL**
Fix #1178

### CODE REVIEW

**Comment by NaridaL** [comment]
Fixes #1178

**Comment by NaridaL** [comment]
This isn't entirely unambiguous, as you could read it as both tsx and jsx are enabled if you set `jsx`, but I didn't really see a way of improving that short of introducing a table.

**Comment by cspotcode** [comment]
Good point; how do you feel about this wording?  Too verbose?  Still ambiguous?

```markdown
**TypeScript Node** works by registering the TypeScript compiler for `.ts`, `.tsx`, `.js`, and `.jsx` extensions.  `.js` and `.jsx` are only registered when allowJs is true.  `.tsx` and `.jsx` are only registered when jsx is enabled.  When node.js has an extension registered (via `require.extensions`), it will use the extension internally for module resolution. When an extension is unknown to node.js, it handles the file as `.js` (JavaScript). By default, **TypeScript Node** avoids compiling files in `/node_modules/` for three reasons:
```

**Comment by NaridaL** [comment]
No, that's better 👍

**Comment by NaridaL** [comment]
I changed it. I left the link in to make it obvious that jsx refers to the compiler option in this context.

**Comment by cspotcode** [comment]
Thanks, I took your lead and also added the best link I could find for allowJs.  If it looks good to you, I'll go ahead and merge.

**Comment by NaridaL** [comment]
Well we both tried to quote jsx at the same time. I guess you were faster 😋 

LGTG

**Comment by cspotcode** [comment]
Perfect, thank you!

**Pull request merged**
