### PR TITLE
Removing subprocess.

### LINKED ISSUE #459: can --inspect be made to bind debug ports for child processes too?
repro steps (I did this on linux and bash):
```
git clone https://github.com/AndrewJDR/inspect-on-forked-processes-doesnt-work
cd inspect-on-forked-processes-doesnt-work
npm i
npm start
```
This starts a child process using cluster.fork(). Note that debugger listens fine on the master process:
```
Debugger listening on ws://127.0.0.1:9229/1ffaac86-3b3f-4097-aa90-df1eba66b6f4
launching child
in the parent: 13039
in the child: 13049
```
And checking netstat shows that 9229 is indeed bound, which is good.
```
$ netstat -lnp | grep 9229
tcp        0      0 127.0.0.1:9229          0.0.0.0:*               LISTEN      13039/node      
```

However, no debugging port is bound for the child process. The output of ps, the `--inspect-port=9230` argument would lead one to believe that a debugger port 9230 is available for the child process:
```
$ ps aux | grep ts-node
13027 pts/30   S+     0:00 sh -c ts-node --inspect -F index.ts
13028 pts/30   Sl+    0:00 node ~/Documents/src/inspect-on-forked-processes-doesnt-work/node_modules/.bin/ts-node --inspect -F index.ts
13039 pts/30   Sl+    0:00 ~/.nvm/versions/node/v9.0.0/bin/node --inspect ~/Documents/src/inspect-on-forked-processes-doesnt-work/node_modules/ts-node/dist/_bin.js -F index.ts
13049 pts/30   Sl+    0:00 ~/.nvm/versions/node/v9.0.0/bin/node ~/Documents/src/inspect-on-forked-processes-doesnt-work/node_modules/ts-node/dist/_bin.js --inspect --inspect-port=9230 ~/Documents/src/inspect-on-forked-processes-doesnt-work/index.ts
```
However, this is unfortunately not the case, looking at netstat output:
```
$ netstat -lnp | grep 9230
(.. nothing to see here ..)
```
Can others reproduce this? If so, can this please be addressed so that we can debug child processes properly?

### LINKED ISSUE #471: Bug/feature:  ts-node should work with NODE_OPTIONS
This works:

```bash
ts-node --inspect-brk foo.ts  # ❤️
```

but this doesn't

```bash
NODE_OPTIONS="--inspect-brk" ts-node foo.ts #  💥
```

I think it's because `ts-node` starts a child process, and because of that, we get an "address already in use" error. See the Node.js help issue attached.

Just try it for yourself and you will see the problem.

### LINKED ISSUE #480: Does not work after upgrading to 4.0.0
`ts-node` just suddenly stop working after upgrading to 4.0.0 (The same with 4.0.1):

nodemon.json
```json
{
	"watch": ["src"],
	"ext": "ts",
	"ignore": ["src/**/*.spec.ts"],
	"exec": "ts-node -P ./tsconfig.json --no-cache ./src/index.ts"
}
```

tsconfig.json
```json
{
	"compilerOptions": {
		"target": "esnext",
		"module": "commonjs",
		"sourceMap": true,
		"lib": ["esnext"],
		"outDir": "build",
		"rootDir": "src",
		"importHelpers": true,
		"noEmitOnError": true,
		"strict": true,
		"noUnusedLocals": true,
		"noUnusedParameters": true,
		"noImplicitReturns": true,
		"noFallthroughCasesInSwitch": true,
		"moduleResolution": "node",
		"experimentalDecorators": true,
		"emitDecoratorMetadata": true
	}
}
```

nodemon: 1.12.5 (dev dependency)
typescirpt: 2.6.2 (dev dependency)
ts-node: 4.0.1 (dev dependency)

Reverted ts-node back to 3.30 solved the problem.

### LINKED ISSUE #487: Repl stopped working after 4.0.0
simply running `ts-node` no longer opens REPL terminal
Rolling back to 3.3.0 fixed it

### LINKED ISSUE #498: Cannot write to stdout in v4 on Windows
After upgrading ts-node to v4.0.0, v4.0.1 or v4.0.2, I cannot write to stdout in Windows.  I had this issue on Node v6.3.0, v8.6.0 and v8.9.3.  For example, these commands print nothing...

```
ts-node -e "console.log('Hello, world!')"
```

```
ts-node -v
```

### PR DESCRIPTION
**Pull request by stelcheck**
This commit:

  1. Cleans up how the code is loaded
  2. Removes the necessity to use 'spawn'

Replaces #476
Replaces #489 

Fixes #459 
Fixes #471 
Fixes #480 
Fixes #487 
Fixes #498 

(phew - hope I don't forget anyone!)

### CODE REVIEW

**Comment by stelcheck** [comment]
One question: I expect that the way I extract flags from minimist that there could be collisions between userland flags and ts-node flags.

**Comment by blakeembrey** [comment]
@stelcheck I think I'm missing something here. How are you using the node.js flags?

**Comment by blakeembrey** [comment]
For reference, it seems like this is undoing https://github.com/TypeStrong/ts-node/pull/131?

**Comment by stelcheck** [comment]
Right... I was thinking they would get applied, but you are right.

I guess we have two options:


  1. Revert to a wrapper not written in Node
  2. Direct users to use NODE_OPTIONS

The first option would be tricky to implement properly I think, so I am trying to implement tjis without a wrapper. What is you take on it?

**Comment by blakeembrey** [comment]
Thanks for your patience. Finally got around to this and closing with https://github.com/TypeStrong/ts-node/pull/536.

**Pull request closed without merging**
