### PR TITLE
fix: tsconfig not found with TS >= 5.3

### LINKED ISSUE #2076: tsconfig not found when extends scope with ts-node>10.0 and typescript@>=5.3.0-dev
### Search Terms

not found tsconfig

### Expected Behavior

no error like ts-node@10.0

### Actual Behavior

```
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
error TS6053: File '@bluelovers/tsconfig/esm/mapfile.json' not found.

    at createTSError (C:\Users\User\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:859:12)
    at reportTSError (C:\Users\User\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:863:19)
    at createFromPreloadedConfig (C:\Users\User\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:874:36)
    at phase4 (C:\Users\User\AppData\Roaming\npm\node_modules\ts-node\src\bin.ts:543:44)
    at bootstrap (C:\Users\User\AppData\Roaming\npm\node_modules\ts-node\src\bin.ts:95:10)
    at main (C:\Users\User\AppData\Roaming\npm\node_modules\ts-node\src\bin.ts:55:10)
    at Object.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\ts-node\src\bin-cwd.ts:5:5)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32) {
  diagnosticCodes: [ 6053 ]
}

```

### Steps to reproduce the problem

global install typescript>=5.3.0-dev
global/local install ts-node@>10.0

```json
{
  "extends": "@bluelovers/tsconfig/esm/mapfile.json",
  "compilerOptions": {
    "disableReferencedProjectLoad": true,
    "importHelpers": true,
    "noPropertyAccessFromIndexSignature": false
  }
}

```

node_modules/ts-node/dist/configuration.js
```js
 const resolvedExtendedConfigPath = tsInternals.getExtendsConfigPath(c.extends, {
                    fileExists,
                    readDirectory: ts.sys.readDirectory,
                    readFile,
                    useCaseSensitiveFileNames: ts.sys.useCaseSensitiveFileNames,
                    trace: tsTrace,
                }, bp, errors, ts.createCompilerDiagnostic);
```

### Specifications

* ts-node version:
* node version:
* TypeScript version:
* tsconfig.json, if you're using one:
```
{}
```
* package.json:
```
{}
```
* Operating system and version:
* If Windows, are you using WSL or WSL2?:

### LINKED ISSUE #2090: extends of tsconfig.json doesn't work when it reference to other package
### Search Terms

`ts-node` `ts-config.json` `extends`

### Expected Behavior

The issue is from `extends` keyword of `tsconfig.json` file, if it reference to a file based location is file, but if it is reference to a pacakge will occur extendee file not found error.

```
{
    "extends": "@tsconfig/node-lts/tsconfig.json"
}
```

In the meanwhile, `tsc` and `jest.config.js` doesn't have this issue.

### Actual Behavior
```
╰─ pnpm test-ts                                                                                                                                                         ─╯

> ts-config-extends@1.0.0 test-ts /Users/anli/Developer/pp/ts-config-extends
> jest --config jest.config.ts --passWithNoTests

Error: Jest: Failed to parse the TypeScript config file /Users/anli/Developer/pp/ts-config-extends/jest.config.ts
  TSError: ⨯ Unable to compile TypeScript:
error TS6053: File '@tsconfig/node-lts/tsconfig.json' not found.
    at readConfigFileAndSetRootDir (/Users/anli/Developer/pp/ts-config-extends/node_modules/.pnpm/jest-config@29.7.0_@types+node@20.9.4_ts-node@10.9.1/node_modules/jest-config/build/readConfigFileAndSetRootDir.js:116:13)
    at async readInitialOptions (/Users/anli/Developer/pp/ts-config-extends/node_modules/.pnpm/jest-config@29.7.0_@types+node@20.9.4_ts-node@10.9.1/node_modules/jest-config/build/index.js:392:15)
    at async readConfig (/Users/anli/Developer/pp/ts-config-extends/node_modules/.pnpm/jest-config@29.7.0_@types+node@20.9.4_ts-node@10.9.1/node_modules/jest-config/build/index.js:147:48)
    at async readConfigs (/Users/anli/Developer/pp/ts-config-extends/node_modules/.pnpm/jest-config@29.7.0_@types+node@20.9.4_ts-node@10.9.1/node_modules/jest-config/build/index.js:424:26)
    at async runCLI (/Users/anli/Developer/pp/ts-config-extends/node_modules/.pnpm/@jest+core@29.7.0_ts-node@10.9.1/node_modules/@jest/core/build/cli/index.js:151:59)
    at async Object.run (/Users/anli/Developer/pp/ts-config-extends/node_modules/.pnpm/jest-cli@29.7.0_@types+node@20.9.4_ts-node@10.9.1/node_modules/jest-cli/build/run.js:130:37)
```

### Steps to reproduce the problem
```
pnpm i
pnpm test-js
pnpm test-ts
```

### Minimal reproduction

https://github.com/kidylee/ts-config-issue-mre

### Specifications

ts-node v10.9.1
node v19.7.0
compiler v5.3.2
```

### PR DESCRIPTION
**Pull request by edosrecki**
Fixes #2076
Fixes #2090

### CODE REVIEW

**Comment by edosrecki** [comment]
Added tests as well.

Before fix:
before-fix

After fix:
after-fix

**Comment by karlhorky** [comment]
This can also be marked as "Fixes #2090" I think

**Comment by edosrecki** [comment]
@karlhorky I marked it but in my opinion author of that issue should close it as duplicate of #2076.

**Comment by karlhorky** [comment]
> author of that issue should close it as duplicate of #2076

Sounds reasonable, yeah. But good to have it also here to clean up the other issue, eg. just in case the author is gone now

**Review by fengmk2 — APPROVED** [review]
LGTM

**Review by alumni — APPROVED** [review]

**Comment by alyahmedaly** [comment]
is there any reason why this PR is not merged?

**Comment by edosrecki** [comment]
Hi @blakeembrey, @cspotcode 

could you please take a look at this PR?

**Comment by fengmk2** [comment]
Can we get the merge and release before Christmas?

**Review by glensc — APPROVED** [review]

**Comment by effektsvk** [comment]
@johnnyreilly I debugged the original issue, the problem was that TypeScript introduced a breaking change in the internal API that is used in ts-node. Here is the comment: https://github.com/microsoft/TypeScript/issues/56492#issuecomment-1823213512

(I hope that is what you're looking for 😅)

**Comment by torokati44** [comment]
> This issue also makes me confused for several hours.
> _**Why not merged until now?**_

+1

This also blocks https://github.com/ruffle-rs/ruffle/pull/14262.

**Comment by alumni** [comment]
Even if this PR gets merged, we would also need a release.

> I'm more wondering why the typical maintainers haven't picked this up - whilst I have the power to hit merge, this isn't a repo I typically work on and I'm looking to understand what the usual maintainers are feeling.

It's open source software, people work on it in their spare time. Maybe they are not even using the latest TS version in their projects, or maybe they don't even work with nodejs anymore. There are a lot of libraries that are like that, e.g. ts-jest is broken since typescript 5.2, typeorm has a ton of pending PRs. I tend not to judge but to have patience :)

**Comment by hilleer** [comment]
> Even if this PR gets merged, we would also need a release.
> 
> > I'm more wondering why the typical maintainers haven't picked this up - whilst I have the power to hit merge, this isn't a repo I typically work on and I'm looking to understand what the usual maintainers are feeling.
> 
> It's open source software, people work on it in their spare time. Maybe they are not even using the latest TS version in their projects, or maybe they don't even work with nodejs anymore. There are a lot of libraries that are like that, e.g. ts-jest is broken since typescript 5.2, typeorm has a ton of pending PRs. I tend not to judge but to have patience :)

Should they be considered the typical maintainers then in this case? 🙂

**Comment by blakeembrey** [comment]
I'm not sure where @cspotcode is right now, but I've been on vacation in South Korea (and will still be here another week). I haven't maintained `ts-node` day to day since @cspotcode has been doing a wonderful job for years now.

That said, if it isn't released in the next day or so I'll look into releasing a new version ASAP.

Thanks for your understanding @alumni. We can't know what's happening with the regular maintainers life so it's best we keep that out of this thread. They may have had some kind of accident or other issue that takes precedence over maintaining code online that they aren't paid or thanked nearly enough for. And even if they were, people sometimes need a break. I'll follow up with @cspotcode when he's back online to make sure everything is ok and ensure someone else can pop in if/when this comes up in the future.

---

@hilleer It'd be best to keep those comments to yourself. A typical maintainer in OSS is actually, yes, working a day job because OSS does not pay. That day job often does have different requirements to the software people maintain. For example, I haven't worked with node professionally for over 7 years, even though I maintain many JavaScript packages.

**Comment by blakeembrey** [comment]
Note to self/maintainers: Will need to create a new branch and redo this comment again the v10 code, since I assume we want this on the latest release and not the v11 beta.

**Comment by hilleer** [comment]
> I'm not sure where @cspotcode is right now, but I've been on vacation in South Korea (and will still be here another week). I haven't maintained `ts-node` day to day since @cspotcode has been doing a wonderful job for years now.
> 
> That said, if it isn't released in the next day or so I'll look into releasing a new version ASAP.
> 
> Thanks for your understanding @alumni. We can't know what's happening with the regular maintainers life so it's best we keep that out of this thread. They may have had some kind of accident or other issue that takes precedence over maintaining code online that they aren't paid or thanked nearly enough for. And even if they were, people sometimes need a break. I'll follow up with @cspotcode when he's back online to make sure everything is ok and ensure someone else can pop in if/when this comes up in the future.
> 
> @hilleer It'd be best to keep those comments to yourself. A typical maintainer in OSS is actually, yes, working a day job because OSS does not pay. That day job often does have different requirements to the software people maintain. For example, I haven't worked with node professionally for over 7 years, even though I maintain many JavaScript packages.

I'm sorry, I think you got it completely wrong. I really did not mean to offend anyone 🙂

**Comment by blakeembrey** [comment]
I merged and released it as [10.9.2](https://github.com/TypeStrong/ts-node/releases/tag/v10.9.2). Took me a while to get it to build and still I'm unclear if I've followed the release process correctly. Hopefully I didn't just break everything 🤞

**Comment by edosrecki** [comment]
@blakeembrey thanks, looks good on my side.

**Comment by rosmcmahon** [comment]
> I'm more wondering why the typical maintainers haven't picked this up - whilst I have the power to hit merge, this isn't a repo I typically work on and I'm looking to understand what the usual maintainers are feeling.

i was beginning to think ts-node was abandonware.

**Pull request merged**
