### PR TITLE
do not depend on @types, which are not runtime libraries

### PR DESCRIPTION
**Pull request by gfx**
`@types/*` is not required for ts-node users. It just adds installation time.

### CODE REVIEW

**Comment by blakeembrey** [comment]
If you can add tests to ensure this is true, I'd be happy to merge it.

**Comment by blakeembrey** [comment]
See https://github.com/TypeStrong/ts-node/issues/475 also.

**Comment by blakeembrey** [comment]
Will merge and make a quick release now, but it'd be good if you could submit tests so this doesn't break anyone.

**Comment by blakeembrey** [comment]
Also, although they are not "runtime" libraries, that doesn't mean they aren't used by people depending on this library. Any types can be transitively exposed by TypeScript, so they would usually be required as a dependency and not a dev dependency. The only reason not to do this, that I can think of, is dependency size. If these deps were on NPM and not GitHub (a separate issue, I can't contribute these definitions easily so never have) I'm not sure it'd be a problem. And if it were, this is really an issue with TypeScript - it shouldn't make dependency management harder than using node.js.

**Comment by gfx** [comment]
Added tests in 3f66c44

**Comment by gfx** [comment]
Wow! PR is merged while I was writing tests 😆

Will make a PR for tests

**Pull request merged**
