### PR TITLE
feat: support .mts .cts

### PR DESCRIPTION
**Pull request by bluelovers**
https://github.com/TypeStrong/ts-node/issues/1007

https://github.com/TypeStrong/ts-node/issues/1414

### CODE REVIEW

**Comment by cspotcode** [comment]
Like all PRs, this will need tests before we can merge it.

**Comment by bluelovers** [comment]
i don't know how make test for this

**Comment by cspotcode** [comment]
A proper test needs to use the feature that you're adding.  So if you're adding support for new file extensions, then the test needs to use the file extensions to prove that ts-node behaves the way you want it to behave.

Most of ts-node's tests are very straightforward.  They run the ts-node CLI and tell it to run code in a sample project.  The code that spawns the CLI lives in `./src/test/**.spec.ts`.  The sample project lives in `./tests`

Here's an example you can use as a starting point.
https://github.com/TypeStrong/ts-node/blob/3a2848c9968f03f7b05e57e833ca256b52ab4e18/src/test/index.spec.ts#L580-L584
https://github.com/TypeStrong/ts-node/tree/main/tests/main-realpath

**Comment by cspotcode** [comment]
This is gonna need more work:

* must register .js extension handler even if allowJs is off
  * necessary to compile .cjs, .cts, and to throw ESM error for .mts
* consider conditionally registering .mjs extension when [moduleType overrides](https://typestrong.org/ts-node/docs/module-type-overrides) are set
* modify `assertScriptCanLoadAsCJSImpl` to understand that .mts overrides package.json
* modify ESM loader to resolve from .mjs / .cjs to .mts / .cts, the same way it does for .js/.jsx/.ts/.tsx

And finally...
* test coverage of the above

**Comment by cspotcode** [comment]
Might want to ship with #1361 so that `require("./foo.cjs")` resolves to `require("./foo.cts")`

**Comment by cspotcode** [comment]
I've merged #1614 into this PR, meant to establish a common core for `_resolveFilename` hooks. In particular, I hope it avoids a painful merge with #1585.

**Comment by cspotcode** [comment]
Docs updates to go with this:

Update moduleTypes jsdoc and markdown: they say ts cannot use mts and cts; this is wrong

**Comment by cspotcode** [comment]
Rolling into #1694

**Pull request closed without merging**
