### PR TITLE
docs(README.md): add troubleshooting tip for syntax errors

### PR DESCRIPTION
**Pull request by jedwards1211**
as discussed in #903.  I had to search for awhile to find that issue and figure out what was going on, and there were some duplicate issues, so I think it would help people to explain this directly in the README.

### CODE REVIEW

**Comment by cspotcode** [comment]
Nice, thanks for writing this up.

We already have this section explaining `SyntaxError`: https://github.com/TypeStrong/ts-node#syntaxerror
Should your explanation be merged into it?

Should we also explain how to identify the difference between a TypeScript syntax error and a node syntax error?  They have different names, so once you know where to look, it's easy and reliable to tell them apart.
I think this may be addressed by merging your additions into the existing `SyntaxError` section.  Perhaps renaming it will also help, something like `SyntaxError vs TSError`?

**Comment by jedwards1211** [comment]
I don't think `SyntaxError vs TSError` would be obvious enough, I had completely failed to notice the `SyntaxError` section because the name of the errors was the last thing on my mind when I stumbled on this issue.  I was thinking "my code compiles with `tsc`, so why does it not work with `ts-node`?"  I thought `ts-node` was somehow invoking an old version of `tsc` or using the wrong compile options.  So I think some version of "my code compiles with `tsc`, so why does it not work with `ts-node`?" is more likely for people to find.

And yeah I think it would be good to merge in what I wrote because I'm not sure the existing explanation there would have been enough to make the light go off in my head.  "cannot be fixed by TypeScript or ts-node. These are runtime issues with your code" sounds like it's saying the mistake is in your code itself, not the transpilation settings.

**Comment by jedwards1211** [comment]
If nothing else adding `Help!` to the title would really help, e.g. `Help! I'm getting a SyntaxError!`, because the `Help!` catches your eye immediately when you're looking for troubleshooting info.

**Comment by jedwards1211** [comment]
Okay I merged my explanation into the syntax error section, see what you think

**Comment by cspotcode** [comment]
Thanks, I haven't forgotten about this.  I'm also working on creating a documentation website in #1207

I may roll these changes into a dedicated website page about errors and how to interpret them.  Not sure yet; it's all a work-in-progress.
https://typestrong.org/ts-node/docs/interpreting-errors

**Comment by cspotcode** [comment]
I ended up adding this to the new "Troubleshooting" page: https://typestrong.org/ts-node/docs/troubleshooting#unsupported-javascript-syntax

I'm going to close this to keep the issue tracker tidy, but please feel free to suggest edits or improvements.  It's been a while since I've looked at this so I may have neglected something obvious, even if we already discussed it.  Thanks again for sending this PR.

**Pull request closed without merging**
