### PR TITLE
Add missing recovery code

### PR DESCRIPTION
**Pull request by hjdivad**
In TypeScript 3.8 there exists a recovery code 1007 for missing braces, which is used for expressions such as:
```
  async function main() {
```

Add this code to `RECOVERY_CODES` to improve the interactive (REPL) experience.

### CODE REVIEW

**Comment by hjdivad** [comment]
I've tested this locally and confirmed this works.

Are there existing tests for `RECOVERY_CODES` I should be updating?  I hadn't noticed any in a cursory look.

**Comment by hjdivad** [comment]
Test failure is not introduced by this pr: it's the same as [in master](https://travis-ci.org/github/TypeStrong/ts-node/jobs/676831580#L430)

**Comment by cspotcode** [comment]
@hjdivad was this causing you problems using the latest version of `ts-node`?  I did a test, and `ts-node` already handles the example you provided.

```
$ npm install ts-node@latest typescript@latest
$ yarn ts-node -vv
ts-node v8.8.2
node v13.8.0
compiler v3.8.3
Done in 0.33s.
$ yarn ts-node
$ /d/Personal-dev/@TypeStrong/ts-node-repros/node_modules/.bin/ts-node
> async function main() {
... }
> 
```

It shows me the ellipsis correctly, allowing me to finish typing the function body.

**Comment by hjdivad** [comment]
@cspotcode hmm the versions look the same as what I was doing, except that I was using node 12.16.1.

I'll take a look tonight or tomorrow and see if I've got something weird in my project or if I can create a minimal reproduction

**Comment by cspotcode** [comment]
@hjdivad thank you, a reproduction would be great.  This seems like a simple enough thing to merge, but I still need to understand what problem it fixes.

**Comment by hjdivad** [comment]
@cspotcode looks like I was mistaken.  Thanks for making me double-check 😄

I was re-evaluating a file a few times and re-defining a function.  The 1007 error was showing up but it was one among several; the real fix was `ts-node -D 2393` (ie ignore duplicate function declaration).

Cheers

**Pull request closed without merging**
