### PR TITLE
feat: scope extension handlers to register path

### PR DESCRIPTION
**Pull request by jstewmon**
This ensures the compiler settings for a given register call are applied when the files under the registered directory are required.

ref: oclif/config/pull/44

### CODE REVIEW

**Comment by blakeembrey** [comment]
This doesn’t seem desirable, can you describe what you’re trying to fix?

**Comment by jstewmon** [comment]
I'm building a plugin-based cli with oclif. Each plugin is defined by a node package in a monorepo.

To facilitate plugin development with TS, oclif registers each plugin root (package in my case) with ts-node.

Since each package has a tsconfig.json file, we need to ensure that when a .ts file is required, it is checked/compiled using its package's tsconfig.json.

Does that make sense?

What seems undesirable to you? I couldn't think how this would be problematic, since requiring a file outside of the registered cwd wouldn't be expected to use the registered settings.

**Comment by jstewmon** [comment]
I looked back over the code and thought of a case where this might not be exactly the right behavior...

The tsconfig.json file is searched for in ancestors of cwd, so I think we should capture that location and check whether the required file is a child of the config file's parent.

This way if you're using ts-node cli in a descendant folder of your project, you can still require files from an ancestral path.

Is that the type of concern you had, or is there more still?

**Comment by jstewmon** [comment]
I figured out that we can use the `fileNames` found when tsconfig is loaded to decide whether to apply the registered settings or not.

**Comment by blakeembrey** [comment]
I think it’s a reasonable change, but it might be an undesirable default behaviour. Some people might rely on this today in the same use case because they extend a global config file. I think it’d be a fantastic addition behind a flag, and relates to another proposal to use different configs per directory too. I can think more about how this configuration should be exposed also.

**Comment by jstewmon** [comment]
Ok, makes sense to me.

How about scope: project | global

**Comment by blakeembrey** [comment]
Happy with even just scope: true or scope: path, but give me some time to think it over this weekend. Maybe scope true just uses CWD by default.

**Comment by blakeembrey** [comment]
The reason it doesn’t help using CWD though is that it doesn’t change over the course of program execution, so we’d need to accept a path or infer that path some how. This can be combined with another flag allowing multiple different scopes to be defined which would solve the other requested use-case too.

**Comment by jstewmon** [comment]
Yeah, I think a path option that defaults to `process.cwd()` makes perfect sense - that would be useful in oclif right away, as it currently has to `chdir` into each plugin root before calling `register`.

I don't have any prior experience using ts-node, so I'm not sure what experienced users expect, but I was surprised that register didn't take a path and bind the discovered settings to the registered path (cwd).

To summarize thus far:
- Add a `path` option to register, which defaults to `process.cwd`
  - The the `path` option is mutually exclusive with `project` option
  - The `path` option is used in place of the `cwd` variable for tsconfig resolution, etc
- Add a `scope` option to register, which defaults to `false`, implying that all required files will be compiled using the same settings.
  - Should we emit a warning or throw an error if `register` is called multiple times with `scope: false`?
  - If scope is true, only apply the registered compiler settings to required files that are in the ts config `fileNames` list after loading and parsing the tsconfig.

Does that accurately capture the direction you want to go?

**Comment by blakeembrey** [comment]
Sounds perfect 👍 I'd even be happy combining `scope` and `path` into a single option, with `boolean | string` input. Internally, seeing `true`, we'd use CWD. Maybe there's a preferred word than scope too, I'll leave that up to you to decide. 

> If scope is true, only apply the registered compiler settings to required files that are in the ts config fileNames list after loading and parsing the tsconfig.

If `scope` is true, I thought we'd want to compile paths only under the specified directly like your PR. Is there a time you'd only want files in `tsconfig.json`? As I write that, it sounds like yes, but beware that today `ts-node` does not use `fileNames` by default. This may be a very tricky one for people to debug also. If you think that's a desired behaviour, and at risk of sounding ridiculous right now, let's add a separate flag for that (unless, again, you feel strongly it should be default when using paths). 

> Should we emit a warning or throw an error if register is called multiple times with scope: false?

For for the error/warning, it's a nice idea. It's been a TODO forever (ref: https://github.com/TypeStrong/ts-node/issues/409) and would be breaking change. Let's push it off for now until the next version.

**Comment by jstewmon** [comment]
> If scope is true, I thought we'd want to compile paths only under the specified directly like your PR. Is there a time you'd only want files in tsconfig.json?

My original issue was that calling register multiple times where each call uses a separate tsconfig.json isn't supported, so the behavior I wanted was for ts-node to use the settings found in tsconfig.json when files to which those should apply are required.

In other words, I want to register project directories with ts-node, and ts-node should do what tsc will do with the ts files in those project directories.

My first pass was to naively apply the compiler settings to only files under the cwd at the time register was called. I later realized that the cwd doesn't directly implicate there the tsconfig settings will be found, since ancestral folders are searched until tsconfig.json is found. So, I determined that the best way to determine which compiler settings should apply to a file is check if the file was in the set of `fileNames` to which typescript determined the tsconfig.json settings apply.

At this point, I see two clear use cases:
- settings are applied globally; register expected to be called once
- settings are project-specific; register scopes compiler settings to fileNames from ts parsing config

I'm not sure what the use case would be for ad-hoc registering compiler settings against a directory, ignoring the fileNames chosen by ts during parsing. Sounds like a bizarre scenario to me.

The `project` and `skipProject` options are at odds with a mode of operation that works like tsc. I've written out ways in which the options could work together, but nothing really made sense.

I suggest we keep it very simple for now and add a new option called `scope`, which can be set to a path. Setting `scope` will have the following effect:
- Settings are loaded from the `tsconfig.json` found in that path's ancestral tree.
- The registered compiler settings only apply to files in the parsed config's `fileNames` list.
- `skipProject` and `project` are ignored or an error is thrown if either are set to indicate invalid usage

>  beware that today ts-node does not use fileNames by default

I'm not exactly sure what effect the `files` option has. The docs that it makes those files load on startup. If it only affects startup behavior, then it makes sense to me that there would be orthogonal settings for specifying the startup behavior and the scope to which a register call applies. I can see how it might be confusing b/c `files` (as an option name) doesn't really express what it does.

**Comment by jstewmon** [comment]
@blakeembrey I think this is ready for more feedback.

I implemented the `scope` option as described in my last comment.

I refactored a few internals to use OOP encapsulation to make it more clear that registerExtensions and shouldIgnore are bound to the settings of a registered compiler instance.

I made it possible to disable a registered compiler, to make testing a little easier (I wanted to ensure only the registered scopes were active in the scope test).

I think in a future, major release, it might be useful if the exported interface was CompilerRegistry or something like that, allowing for introspection/management of all registered compilers.

**Comment by jstewmon** [comment]
Hmm... the typescript 2.0 test configuration is failing b/c I used esModuleInterop in the scope test, but that setting was added in 2.7. Any suggestions for a different setting that can be used to verify that the right settings are applied to the scope?

**Comment by blakeembrey** [comment]
You can definitely add to the exports, not sure on the scope of the changes now though. I’d prefer not to use classes, they aren’t necessary here. I can tidy this up though according to your vision. Can you explain why you want to nullify project options when scope is used? I assume they are valid to be used together - say I want to put all my configs in one directory apart from my code?

**Comment by jstewmon** [comment]
> say I want to put all my configs in one directory apart from my code

I sought to support that, but it's a pain b/c Typescript is strict in its convention that a tscofig.json belongs at the "root" of the "project".

The `configFileName` property passed to `parseJsonConfigFileContent` is significant b/c it serves as the baseUrl for files that are discovered. `configFileName` can be passed as undefined, in which case the `baseUrl` will be used, but a different set of default `compilerOptions` will be selected.

I finally asked myself why I was fighting against the typescript toolchain for an arbitrary requirement, for which I didn't know of any practical use case...

For lack of a better description, using `scope` means behaving like `tsc`. `tsc` requires that you have a `tsconfig.json` file at the project root, which means `scope` is inherently incompatible with `project` and `skipProject`.

**Comment by blakeembrey** [comment]
This will break for people who use a different file name though, which is common. Not just a different directory. I don’t think there’s much fighting to be done, by default we don’t use anything outside compiler options and don’t care what directory things live in. The config path can still be elsewhere in any case.

**Comment by blakeembrey** [comment]
Would you mind if I take another PR attempt at what we have described and share it with you to review?

**Comment by jstewmon** [comment]
Sure, go for it.

> This will break for people who use a different file name though, which is common

`ts.findConfigFile` supports passing an alternate name, but I didn't see a way to support that without making the options very confusing.

Maybe if `scope` were just a `bool`, `project` could be a path to a file or directory, then those two options would work together, but the fileNames wouldn't be correct if the config is outside of the source tree.

**Comment by blakeembrey** [comment]
The file names don’t matter, that’s what I’m trying to say. I’d remove that from even being parsed if I had the time to fix it, since it’s an unnecessary operation for us. As for the path, we already support a directory or file, you’re removing that support when the scope flag is set which is confusing me.

**Comment by jstewmon** [comment]
> The file names don’t matter

Do you mean the filenames in the config object returned by `parseJsonConfigFileContent`? If so, then we disagree (or misunderstand each other) on this point. Those filenames are the files to which the parsed `tsconfig.json` applies, so they are the exact set of files to which the scoped compiler should apply.

**Comment by jstewmon** [comment]
> But why not just have it scope to a directory?

Because that is not what `tsc` will do. All I want is a way of making ts-node behave like tsc.

I tried to provide the context before; maybe it didn't resonate. I'll try to restate it...

I have a monorepo with several packages that will be built with tsc (each package adheres to tsc constraints, having a tsconfig.json file in the package root). Some of those packages are plugins for an oclif-based cli.

When the oclif-based cli is run from the source repository, as a convenience, it dynamically registers each plugin package with ts-node, so that developers can run the cli, picking up changes made to  the ts sources without having to run tsc after editing a file.

Currently, this convenience feature is rather inconvenient for me because the settings in each of my package's tsconfig.json files are not applied by ts-node the same way as they are applied by tsc.

Not sure it makes it more clear, maybe reviewing the discussion on https://github.com/oclif/config/pull/44 would help. That's the PR I opened for the relevant oclif change that would follow this PR.

**Comment by blakeembrey** [comment]
@jstewmon I understand what you want to do. I'm trying to ask why you want one approach over another. Given that this will never work like `tsc` - it takes a script to execute and spiders out from there, why do you want to so strongly tie it to a behaviour node.js can't follow? It may create more problems in the future if we ever want to skip the `fileNames` resolution which is really a wasted look up in the compiler today. Like I said, if that's really what you want to do, that's fine also, but it shouldn't rewrite too much of the package or use classes - let's keep the change simple.

**Comment by jstewmon** [comment]
In my project I have tsconfig.json files in each project root that includes the `src` directory, and I have a tsconfig in each project's test directory (sibling to src). If I make two register calls, one for the project and another for its test directory, then the order in which I register them will affect the settings that are used to compile test files (if I register the project after the tests, my tests would compile using the project's settings).

That doesn't actually impact the issue I have with oclif, but I was aware of it being a case that might violate someone's expectations. Honestly, it never occurred to me that there'd be an objection to using fileNames - I didn't suggest it initially b/c I didn't know it would be available. And, it didn't occur to me that it would be a wasted step, since tsc will transpile all files. I see your point that it isn't necessary for ts-node, since it may not transpile all files, but the cost is only paid when register is called, which I wouldn't expect to be often, since currently only calling once is supported.

I can revise the PR to eliminate the class - it made the code easier for me to grok and allowed for the disabling of a registered compiler, but I can make that work with just functions and a plain object.

**Comment by blakeembrey** [comment]
That’s one of the tricky parts I’d like to better understand here for sure, as I imagine it being the largest use-case. I’m happy to use the file names if we expect there to be no overlap in general use, or even just as an experiment and introduce directories later. In this case do we expect these two different configuration files to apply to distinct sets, or is there some level of overlap? If there’s some level of overlap, that’s my largest concern, because we can’t easily tell if something was already transpiled. That can result in hard to debug issues which regularly get logged today already. We also need to consider how this flag will be used to ensure we aren’t double registering in the future - does it make sense that the list is the source of truth always and any overlap with a second list is an explicit error? 

I’m only trying to optimise, selfishly, for minimum number of issues logged here. Path of least confusion. I agree that up front both feel perfectly fine and I’m happy to experiment with both, just wanted to share some possibilities. I’m very sorry it turned into a lot of discussion instead of straightforward implementation, because in either case I clearly agree it’s a valuable feature. It’s just the unknown usage that I can’t yet imagine that I want to ensure we are using the most obvious and future proof direction.

I believe this feature has extremely large overlap with https://github.com/TypeStrong/ts-node/issues/655 also, so it’s definitely part of the reason I don’t want to fragment any approach here. 

There’s one very tricky problem here also. If we support this, it doesn’t produce real files. That means no definition file is produced. If the main project then requires another which has a slightly different configuration, it won’t have any way to get the type information. This seems like a serious issue.

**Comment by jstewmon** [comment]
> I’m very sorry it turned into a lot of discussion instead of straightforward implementation

No worries - I understand the need to approach this change with caution. I've just started to feel a bit of stress due to the amount of time I'm directing at this issue. I'm eager to figure out the right solution. :-)

I had assumed that the filenames would never overlap. If two register calls include the same filename, I think throwing an error is helpful b/c it's a case where one of the register calls is not going to have the expected result. We could always support an option to not throw in the future if someone has a use case for it.

#655 is interesting - it does overlap, but I think it's a different mode of operation. It's basically asking for dynamic compiler registration. When a file is required, find the compiler that applies to it; if none found, find the relevant tsconfig.json and register a new compiler. This type of feature is what I had in mind when I previously suggested making a CompilerRegistry, which could be used manage the set of registered compilers.

> If we support this, it doesn’t produce real files. That means no definition file is produced. If the main project then another project which has a different instance transpiling, it won’t have any way to get the type information. This seems like a serious issue. Do you have any thoughts on this?

I need to do some testing around this one. I want to say project references will allow for this. If it does, it might violate the expectation that a filename only appears once among all compilers.

**Comment by blakeembrey** [comment]
The tricky part with having multiple instances with different files is because the errors may be different. For instance, in strict mode. We would definitely need to resolve the definition first over the TypeScript file on demand. Based on this, it might be worth combining these two requests and using the compiler instances to look up a definition before we look up the real file in the file system. It’s definitely a more complicated feature, I’m sorry I overlooked this problem from the start. For example, implicit any means we need to get the definition output and not the TypeScript file since it won’t compile with a stricter configuration. Same with any target differences, lib, types, etc. This is primarily because TypeScript will still look up these files to resolve the type definitions, not for the runtime itself.

**Comment by jstewmon** [comment]
I'm very confused by your last comment. I probably just don't have enough context for it to make sense to me.

Are you just talking about the repl behavior?

**Comment by blakeembrey** [comment]
@jstewmon Sorry for the long delay, work has been busy and haven't had time to type out a thoughtful response. What do you think of the new `references` feature and could it be useful for this feature? I typed out some thoughts in https://github.com/TypeStrong/ts-node/issues/135#issuecomment-421522197. Basically, we can use each `tsconfig.json/includes` to decide whether something should compile, and `references` to load up additional contexts such as this PR.

**Comment by jstewmon** [comment]
No worries - I've been busy on another project as well. I should have some time next week to revisit this issue. I do think that `references` will apply to this feature, but I'm not sure how yet.

**Comment by blakeembrey** [comment]
I'm revisiting old PRs and will land something similar to this request, I believe it's not too large of a feature (it's a combination of 2 features, one already landed here: https://github.com/TypeStrong/ts-node/commit/a7df13787853df42b75ba93ed1bab679a37f5438). The only other feature I see in this PR is the ability to enable/disable dynamically. One thing I see missing in this PR is `--scope` avoiding compiling files outside its scope, which I'll also add.

**Comment by blakeembrey** [comment]
Dynamic enable/disable here: https://github.com/TypeStrong/ts-node/commit/85aa2d3b167e98c7deb6e49f8d1ad9eef55e4511.

**Comment by blakeembrey** [comment]
Scoped support enabled here: https://github.com/TypeStrong/ts-node/commit/c1c22f8064bcc3220ab104bbed6875ca406fa81c.

**Pull request closed without merging**
