### PR TITLE
Update AVA recipe

### PR DESCRIPTION
**Pull request by novemberborn**
* Fix spelling
* Add AVA 4 config

### CODE REVIEW

**Comment by cspotcode** [comment]
Thanks for this.  Is AVA 4 released yet?  If so, would you mind putting the AVA 4 config above the AVA 3 config? I figure it's better for people to see the most recommended, up-to-date configs at the top of the page, and need to scroll down for older, out-of-date stuff.  What do you think?

**Comment by novemberborn** [comment]
`npm i ava@latest` still gives you AVA 3, so I think that should remain at the top.

**Comment by cspotcode** [comment]
Is AVA 4 unstable? is it recommended for new users?  I want to understand
in case I get tickets about it.

**Comment by novemberborn** [comment]
It's a prerelease, alpha at the moment, though that's more a reflection on planned breaking changes than an assessment of stability.

Perhaps add "(available as a prerelease)"?

**Comment by cspotcode** [comment]
I took me a while to get back to this, but I ended up rolling it into #1297
https://typestrong.org/ts-node/docs/recipes/ava

The prerelease stuff is commented out but we can update the docs when it's out of prerelease.  I just want to keep things simple on my end.

**Comment by novemberborn** [comment]
Great!

**Pull request closed without merging**
