### PR TITLE
:memo: mocha watch

### PR DESCRIPTION
**Pull request by basarat**
Merge if happy :rose:

### CODE REVIEW

**Comment by blakeembrey** [comment]
I'd be happy to merge the section together, if that makes sense. Also, does Mocha have a transpiler option that works for both? IIRC, it's something like `--extension ts:ts-node`. Been a long while since I used Mocha myself.

**Comment by basarat** [comment]
> IIRC, it's something like --extension ts:ts-node. Been a long while since I used Mocha myself.

I searched long and hard to find `watchExtensions`. Seems to be the only way in town.

**Comment by blakeembrey** [comment]
@basarat Oh, it's `--compilers` - did you try it? https://github.com/mochajs/mocha/blob/master/bin/_mocha#L81

**Comment by blakeembrey** [comment]
It seems like it does both automatically: https://github.com/mochajs/mocha/blob/master/bin/_mocha#L297-L306. I think the reason I avoided it in the beginning was the duplication of having to do `--compilers ts:ts-node --compilers tsx:ts-node`.

**Comment by basarat** [comment]
I just did a blind run (i.e. didn't investigate if what was proposed made sense). Didn't work :rose: 

screen shot 2016-06-28 at 3 18 40 pm

**Comment by blakeembrey** [comment]
Thanks! I think I missed something though - I'm guessing it should be `ts-node/register` in both those places.

**Comment by basarat** [comment]
> I think I missed something though - I'm guessing it should be ts-node/register in both those places.

Indeed it worked! :rose: `mocha --compilers ts:ts-node/register --compilers tsx:ts-node/register` 

We can change the default `--require` to `--compilers` and then `--watch` is intutive. How does that sound?

**Comment by blakeembrey** [comment]
Great! 👍

**Comment by basarat** [comment]
closing in favor of : https://github.com/TypeStrong/ts-node/pull/140

**Pull request closed without merging**
