### PR TITLE
chore: remove unused devDependency

### PR DESCRIPTION
**Pull request by Songkeys**
`ntypescript` is deprecated and unused

### CODE REVIEW

**Comment by cspotcode** [comment]
It's there so we can test our `compiler` option.  If it's unused, that probably means we have a mistake in our automated tests, because they are supposed to be using `ntypescript`.

**Comment by Songkeys** [comment]
That's weird. I removed it and still passed all the tests locally. Could you please check that? Maybe I was wrong.

```
codespace ➜ /workspaces/ts-node (patch-2) $ npm run test

> ts-node@10.2.0 test
> npm run build && npm run lint && npm run test-cov --


> ts-node@10.2.0 build
> npm run build-nopack && npm run build-pack


> ts-node@10.2.0 build-nopack
> npm run build-tsc && npm run build-configSchema


> ts-node@10.2.0 build-tsc
> tsc


> ts-node@10.2.0 build-configSchema
> typescript-json-schema --topRef --refs --validationKeywords allOf --out tsconfig.schema.json tsconfig.build-schema.json TsConfigSchema && node --require ./register ./scripts/create-merged-schema


> ts-node@10.2.0 build-pack
> node ./scripts/build-pack.js


> ts-node@10.2.0 lint
> prettier --check .

Checking formatting...
All matched files use Prettier code style!

> ts-node@10.2.0 test-cov
> nyc ava


  119 tests passed
------------------------------|---------|----------|---------|---------|----------------------------------------------------------------------------------------------------------------------------
File                          | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s                                                                                                          
------------------------------|---------|----------|---------|---------|----------------------------------------------------------------------------------------------------------------------------
All files                     |   83.36 |    73.74 |   86.22 |   84.46 |                                                                                                                            
 ts-node                      |       0 |      100 |     100 |       0 |                                                                                                                            
  esm.mjs                     |       0 |      100 |     100 |       0 | 3-11                                                                                                                       
 ts-node/dist-raw             |   82.63 |    68.42 |   81.97 |   82.54 |                                                                                                                            
  node-cjs-helpers.js         |     100 |      100 |     100 |     100 |                                                                                                                            
  node-cjs-loader-utils.js    |   90.91 |    78.13 |     100 |   90.38 | 50,82-84,131                                                                                                               
  node-errors.js              |      50 |        0 |      40 |      50 | 9,19,26                                                                                                                    
  node-internal-fs.js         |   88.89 |       50 |     100 |    87.5 | 11                                                                                                                         
  node-options.js             |   78.95 |     62.5 |     100 |   78.38 | 64-69,75-76,88,98                                                                                                          
  node-package-json-reader.js |   84.21 |       75 |     100 |   84.21 | 19,36-37                                                                                                                   
  node-primordials.js         |    61.9 |      100 |      60 |    61.9 | 4-5,20,25,27-28,30,32                                                                                                      
  node-repl-await.js          |   82.29 |    63.93 |     100 |   82.98 | 164-195                                                                                                                    
 ts-node/esm                  |       0 |      100 |     100 |       0 |                                                                                                                            
  transpile-only.mjs          |       0 |      100 |     100 |       0 | 3-11                                                                                                                       
 ts-node/register             |      25 |      100 |     100 |      25 |                                                                                                                            
  files.js                    |       0 |      100 |     100 |       0 | 1                                                                                                                          
  index.js                    |     100 |      100 |     100 |     100 |                                                                                                                            
  transpile-only.js           |       0 |      100 |     100 |       0 | 1                                                                                                                          
  type-check.js               |       0 |      100 |     100 |       0 | 1                                                                                                                          
 ts-node/src                  |   84.07 |    74.67 |   87.37 |   85.55 |                                                                                                                            
  bin-cwd.ts                  |     100 |      100 |     100 |     100 |                                                                                                                            
  bin-script-deprecated.ts    |       0 |      100 |     100 |       0 | 3-10                                                                                                                       
  bin-script.ts               |     100 |      100 |     100 |     100 |                                                                                                                            
  bin-transpile.ts            |       0 |      100 |     100 |       0 | 3-5                                                                                                                        
  bin.ts                      |   92.79 |     93.8 |   85.71 |   93.58 | 292-295,378,381,399-400,407                                                                                                
  configuration.ts            |    96.2 |    93.48 |     100 |   97.33 | 116,147                                                                                                                    
  esm.ts                      |   92.86 |     87.5 |     100 |   92.73 | 46,57,63,138                                                                                                               
  index.ts                    |   84.03 |    75.92 |   81.58 |   85.32 | 144,148-151,556,563,631,635,642,672-673,700,753-754,887,892,942-954,1035,1062,1067-1076,1088-1108,1118-1120,1128,1417-1431 
  module-type-classifier.ts   |     100 |    88.89 |     100 |     100 | 80-92                                                                                                                      
  repl.ts                     |    90.5 |    79.39 |   94.29 |   91.53 | 228-229,276,287-292,300,323-328,368-369,395-396                                                                            
  resolver-functions.ts       |   89.13 |    74.19 |   90.91 |   90.91 | 112-120                                                                                                                    
  ts-internals.ts             |   54.79 |    34.17 |   82.76 |   58.21 | 47-52,70-73,104-105,160-161,179,208-213,231-294,311,317-332,345-347,354                                                    
  tsconfigs.ts                |   72.22 |    53.33 |     100 |   73.33 | 19-23                                                                                                                      
  util.ts                     |     100 |       85 |   88.89 |     100 | 10-11,46                                                                                                                   
 ts-node/src/transpilers      |   86.49 |       70 |     100 |   86.49 |                                                                                                                            
  swc.ts                      |   86.49 |       70 |     100 |   86.49 | 24,30-33,40                                                                                                                
 ts-node/transpilers          |     100 |      100 |     100 |     100 |                                                                                                                            
  swc-experimental.js         |     100 |      100 |     100 |     100 |                                                                                                                            
------------------------------|---------|----------|---------|---------|----------------------------------------------------------------------------------------------------------------------------
```

**Comment by cspotcode** [comment]
It looks like whatever test we had which used ntypescript has been accidentally removed.  I'm not sure when it was removed, and I'm not sure the easiest way to find it in the git history so we can re-add it.

**Comment by Songkeys** [comment]
That's so sad. Maybe you could quickly browse it with <https://githistory.xyz/TypeStrong/ts-node/blob/main/src/test/index.spec.ts>. You still need to browse each file manually though. Not sure if there's a easier way...

**Comment by cspotcode** [comment]
Closing in favor of #1437; feel free to move discussion to that issue.

**Comment by zeen** [comment]
@cspotcode Should this be reopened? Looks like #1437 is resolved, while `ntypescript` remains unused and deprecated.

**Comment by cspotcode** [comment]
Yeah makes sense.  Thought it's worth pointing out, since we're talking about an automated test, not a prod dependency, it would be perfectly fine to keep using deprecated ntypescript to serve that purpose.  But if it's not being used at all, and we have other tests, makes sense to remove it.

**Comment by cspotcode** [comment]
Looks like the ntypescript dep was removed in #1951

**Pull request closed without merging**
