### PR TITLE
Add notes about watching and restarting

### PR DESCRIPTION
**Pull request by whitecolor**
Add notes how to configure watching and starts

### CODE REVIEW

**Comment by blakeembrey** [comment]
Any reason for closing?

**Comment by roblav96** [comment]
@blakeembrey Honestly I would still merge this PR. I just went around a loop seeking this information and ended back here. lol

**Comment by whitecolor** [comment]
I reopened it, if you wish this info in readme, let it be.

**Comment by roblav96** [comment]
@whitecolor It must be, Dilly Dilly! 🍻

**Pull request merged**
